---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины

non-functional:
  - Сайт должен быть доступен на различных устройства
  - Сайт должен иметь мобильную версию
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - Сайт должен быть интуитивно понятен пользователям
  - Вносить правки на сайте могут только руководители выше среднего звена
  - Сайт должен соответствовать требованиям Роскомнадзора





